/**
 * Build the browser half into the ModuleLoader bundle the web shell serves.
 *
 * `@deepseek-ai/dsh-client-modules` serves each enabled Loader entry's
 * `exports['./client']` verbatim, so `lib/client.js` must already be the
 * `window.__ModuleLoader__.load({...})` artifact this checkout's shipped
 * packages carry. There is no bundler in this repository on purpose: the plugin
 * imports nothing but the statically seeded `react` and
 * `@deepseek-ai/dsh-client-ui-primitives`, and `src/notebook.js` is spliced in
 * as one shared source of truth for the Node and browser halves.
 *
 * Usage:
 *   node scripts/build-client.mjs           rewrite lib/client.js
 *   node scripts/build-client.mjs --check   fail when lib/client.js is stale
 */
import { readFile, writeFile } from 'node:fs/promises'
import { createHash } from 'node:crypto'
import { fileURLToPath } from 'node:url'

const root = new URL('../', import.meta.url)
const read = (relative) => readFile(new URL(relative, root), 'utf8')

/**
 * Turn an ES module whose exports all start their own line into a fragment that
 * can be spliced into a function body.
 * @param source - the module text.
 * @returns the fragment.
 */
function stripExports(source) {
  return source.replace(/^export /gm, '')
}

/**
 * Compose the served bundle.
 * @param name - the package name, which is also the module id.
 * @param notebook - `src/notebook.js` text.
 * @param clientUi - `src/client-ui.js` text.
 * @returns the bundle text.
 */
function compose(name, notebook, clientUi) {
  // A hash of the sources, not a timestamp: the build stays deterministic (so
  // `--check` can compare byte for byte) while the running page can still say which
  // revision it carries — which answers "is my tab serving a stale bundle?".
  const buildId = createHash('sha256').update(notebook).update(clientUi).digest('hex').slice(0, 8)
  return `// Generated by scripts/build-client.mjs — edit src/notebook.js and src/client-ui.js, then rebuild.
window.__ModuleLoader__.load({
	id: ${JSON.stringify(name)},
	factory: (require) => {
		var module = { exports: {} };
		var exports = module.exports;
		Object.defineProperty(exports, Symbol.toStringTag, { value: "Module" });
		const React = require("react");
		const BUILD_ID = ${JSON.stringify(buildId)};
${stripExports(notebook)}
${clientUi}
		return module.exports;
	}
});
`
}

const manifest = JSON.parse(await read('package.json'))
const name = manifest.name
if (typeof name !== 'string' || name.length === 0) {
  console.error('package.json has no name')
  process.exit(1)
}

const notebook = await read('src/notebook.js')
const clientUi = await read('src/client-ui.js')
const composed = compose(name, notebook, clientUi)
const target = new URL('lib/client.js', root)

if (process.argv.includes('--check')) {
  let current
  try {
    current = await readFile(target, 'utf8')
  } catch {
    console.error('lib/client.js is missing; run: node scripts/build-client.mjs')
    process.exit(1)
  }
  if (current !== composed) {
    console.error('lib/client.js is stale; run: node scripts/build-client.mjs')
    process.exit(1)
  }
  console.log('lib/client.js is up to date')
  process.exit(0)
}

await writeFile(target, composed, 'utf8')
const id = /const BUILD_ID = "([0-9a-f]+)"/.exec(composed)
console.log(`wrote lib/client.js (${composed.length} bytes, module id ${name}, build ${id === null ? '?' : id[1]})`)
